name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.18
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  file_picker: ^10.3.3
  flutter_slidable: ^4.0.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  http: ^1.5.0
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: any
  on_audio_query: ^2.9.0
  youtube_explode_dart: ^2.5.2
  youtube_player_flutter: ^9.1.2
  google_sign_in: ^7.2.0
  device_info_plus: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Add assets section
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
